version: 1.0
jobs:
  - type: webproject
    source: prepackaged
    sitekey: digitall 
  - type: asset
    fetch: http
    username: NEXUS_USERNAME
    password: NEXUS_PASSWORD
    source: https://devtools.jahia.com/nexus/service/local/artifact/maven/redirect?r=jahia-snapshots&g=org.jahia.test&a=jahia-test-module&v=LATEST
    filepath: /tmp/jahia-test-module-LATEST.jar
  - type: module
    id: jahia-test-module
    filepath: /tmp/jahia-test-module-LATEST.jar
  - type: asset
    fetch: http
    username: NEXUS_USERNAME
    password: NEXUS_PASSWORD
    source: https://devtools.jahia.com/nexus/service/local/artifact/maven/redirect?r=jahia-snapshots&g=org.jahia.modules&a=graphql-dxm-provider&v=LATEST
    filepath: /tmp/graphql-dxm-provider-LATEST.jar
  - type: module
    id: graphql-dxm-provider
    filepath: /tmp/graphql-dxm-provider-LATEST.jar
  - type: asset
    fetch: http
    username: NEXUS_USERNAME
    password: NEXUS_PASSWORD
    source: https://devtools.jahia.com/nexus/service/local/artifact/maven/redirect?r=jahia-snapshots&g=org.jahia.test&a=graphql-test&v=LATEST
    filepath: /tmp/graphql-test-LATEST.jar
  - type: module
    id: graphql-test
    filepath: /tmp/graphql-test-LATEST.jar
